require 'rtoolchain/targets/gcctarget'

module RToolchain
  module Targets
    module GCC
      class Darwin < GCCTarget

        target 'darwin'

        # Darwin Options

        long_option :flag => '-all_load'
        long_option :flag => '-allowable_client'
        long_option :flag => '-arch'
        long_option :flag => '-arch_errors_fatal'
        long_option :flag => '-arch_only'
        long_option :flag => '-bind_at_load'
        long_option :flag => '-bundle'
        long_option :flag => '-bundle_loader'
        long_option :flag => '-client_name'
        long_option :flag => '-compatibility_version'
        long_option :flag => '-current_version'
        long_option :flag => '-dead_strip'
        long_option :flag => '-dependency-file'
        long_option :flag => '-dylib_file'
        long_option :flag => '-dylinker_install_name'
        long_option :flag => '-dynamic'
        long_option :flag => '-dynamiclib'
        long_option :flag => '-exported_symbols_list'
        long_option :flag => '-filelist'
        long_option :flag => '-flat_namespace'
        long_option :flag => '-force_cpusubtype_ALL'
        long_option :flag => '-force_flat_namespace'
        long_option :flag => '-headerpad_max_install_names'
        long_option :flag => '-iframework'
        long_option :flag => '-image_base'
        long_option :flag => '-init'
        long_option :flag => '-install_name'
        long_option :flag => '-keep_private_externs'
        long_option :flag => '-multi_module'
        long_option :flag => '-multiply_defined'
        long_option :flag => '-multiply_defined_unused'
        long_option :flag => '-noall_load'
        long_option :flag => '-no_dead_strip_inits_and_terms'
        long_option :flag => '-nofixprebinding'
        long_option :flag => '-nomultidefs'
        long_option :flag => '-noprebind'
        long_option :flag => '-noseglinkedit'
        long_option :flag => '-pagezero_size'
        long_option :flag => '-prebind'
        long_option :flag => '-prebind_all_twolevel_modules'
        long_option :flag => '-private_bundle'
        long_option :flag => '-read_only_relocs'
        long_option :flag => '-sectalign'
        long_option :flag => '-sectobjectsymbols'
        long_option :flag => '-whyload'
        long_option :flag => '-seg1addr'
        long_option :flag => '-sectcreate'
        long_option :flag => '-sectobjectsymbols'
        long_option :flag => '-sectorder'
        long_option :flag => '-segaddr'
        long_option :flag => '-segs_read_only_addr'
        long_option :flag => '-segs_read_write_addr'
        long_option :flag => '-seg_addr_table'
        long_option :flag => '-seg_addr_table_filename'
        long_option :flag => '-seglinkedit'
        long_option :flag => '-segprot'
        long_option :flag => '-segs_read_only_addr'
        long_option :flag => '-segs_read_write_addr'
        long_option :flag => '-single_module'
        long_option :flag => '-static'
        long_option :flag => '-sub_library'
        long_option :flag => '-sub_umbrella'
        long_option :flag => '-twolevel_namespace'
        long_option :flag => '-umbrella'
        long_option :flag => '-undefined'
        long_option :flag => '-unexported_symbols_list'
        long_option :flag => '-weak_reference_mismatches'
        long_option :flag => '-whatsloaded'
        short_option :flag => '-F', :multiple => true, :name => :framework_dir
        long_option :flag => '-gused'
        long_option :flag => '-gfull'
        long_option :flag => '-mmacosx-version-min=version'
        long_option :flag => '-mkernel'
        long_option :flag => '-mone-byte-bool'

      end
    end
  end
end
